### PR TITLE
Fix at php blade directive

### PR DESCRIPTION
**Pull request by ThibaudDauce**
Currently @php @endphp on multiple lines do not work.

I had a problem with the use of `{{ config(…) }}` (cannot echo mixed) and I wanted to add doc blocks for PHPStan to understand the content:
```blade
@php
/** @var string */
$value = config(…);
@endphp

{{ $value }}
```

But the current implementation discard multiple lines PHP code.

Maybe the following code is also broken (it's not pretty but I think there should be reason to have new lines inside `{{ … }}` or other Blade directives.

```blade
{{ $user
    ->name }}
```

I will try to push a fix of the implementation for this problem.

### CODE REVIEW

**Comment by canvural** [comment]
I think this is an issue about the [regex](https://github.com/canvural/phpstan-blade-rule/blob/main/src/Compiler/BladeToPHPCompiler.php#L62) we use. And the fix will be really easy, we just need to add `s` regex modifier to the regex.

New regex should be `'#(/\*\* file: .*?, line: \d+ \*/)?.*?<\?php(.*?)\?>#s'`

Can you try that before investing more time into this?

**Comment by ThibaudDauce** [comment]
With the `#s` the result is 

```
<?php
/** file: multiple-lines-at-php-directive.blade.php, line: 1 */ 
/** file: multiple-lines-at-php-directive.blade.php, line: 2 */    /** @var string */
/** file: multiple-lines-at-php-directive.blade.php, line: 3 */    $database = config('database.default');
/** file: multiple-lines-at-php-directive.blade.php, line: 4 */
```

It should be:
```
<?php
/** file: multiple-lines-at-php-directive.blade.php, line: 1 */
/** @var string */
/** file: multiple-lines-at-php-directive.blade.php, line: 2 */
$database = config('database.default');
```

No? (with the comments on separate lines?)

**Comment by canvural** [comment]
That looks correct.

The pretty print method of PHP parser puts the comments to new line, not the compiler.

That also discovers another issue I think. The PHP parser only sees one comment above a statement. So I think
```php
/** file: multiple-lines-at-php-directive.blade.php, line: 2 */    /** @var string $database */
/** file: multiple-lines-at-php-directive.blade.php, line: 3 */    $database = config('database.default');
```
would definitely cause some issues. Maybe we can combine the doc nodes into one. But that's some extra work. I'll be happy to  do it if you don't want to invest lots of time.

**Comment by ThibaudDauce** [comment]
Ok nice (I was working on a fix but if `#s` is working fine I'll add it to the PR).

Yes I was expecting problems with the docblock not directly in front of the PHP line. I will look into it to see if there is a simple way to merge docblocks.

**Comment by ThibaudDauce** [comment]
Hum, the `#s` is not working as expected for the other tests…

```
1) Vural\PHPStanBladeRule\Tests\Compiler\BladeToPHPCompilerTest::it_compiles_blade_content with data set "Multiple lines template" ('multiple-lines')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 \n
 /** file: multiple-lines.blade.php, line: 1 */\n
 echo $name;\n
-/** file: multiple-lines.blade.php, line: 2 */\n
+/** file: multiple-lines.blade.php, line: 1 */\n
 echo $age;'

/home/thibaud/Code/phpstan-blade-rule/tests/Compiler/BladeToPHPCompilerTest.php:39

2) Vural\PHPStanBladeRule\Tests\Compiler\BladeToPHPCompilerTest::it_compiles_blade_content with data set "Multiple lines template with HTML" ('multiple-lines-with-html')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 \n
 /** file: multiple-lines-with-html.blade.php, line: 1 */\n
 echo $name;\n
-/** file: multiple-lines-with-html.blade.php, line: 3 */\n
+/** file: multiple-lines-with-html.blade.php, line: 1 */\n
 echo $age;'

/home/thibaud/Code/phpstan-blade-rule/tests/Compiler/BladeToPHPCompilerTest.php:39

3) Vural\PHPStanBladeRule\Tests\Compiler\BladeToPHPCompilerTest::it_compiles_blade_content with data set "Multiple lines @php directive" ('multiple-lines-at-php-directive')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '<?php\n
 \n
 /** file: multiple-lines-at-php-directive.blade.php, line: 1 */\n
+/** file: multiple-lines-at-php-directive.blade.php, line: 2 */\n
 /** @var string */\n
-/** file: multiple-lines-at-php-directive.blade.php, line: 2 */\n
-$database = config('database.default');'
+/** file: multiple-lines-at-php-directive.blade.php, line: 3 */\n
+$database = config('database.default');\n
+/** file: multiple-lines-at-php-directive.blade.php, line: 4 */'
```

**Comment by ThibaudDauce** [comment]
I made some tests:
`/** file: multiple-lines-at-php-directive-with-comments.blade.php, line: 3 @var string */` is failing (https://phpstan.org/r/6efedfbb-7c0b-4a6b-8abd-db7dbcae52e9)

but `/** @var string file: multiple-lines-at-php-directive-with-comments.blade.php, line: 3 */` is working (https://phpstan.org/r/f6ef1728-072d-4208-ab2b-e86d50f8a461)

So if we merge docblocks we need to prepend and not append. I don't have time right now (I need to go) but I will try this next week.

Thanks again for the awesome work!

PS: I think my solution for the multi-line in this PR is really complex, feel free to improve it if you have a better idea. I couldn't find something else than parsing the string PHP/HTML part by part. With the tests it's easy to try other things. But maybe this solution could help us with the dockblocks problem since we are in total control of each line.

**Comment by canvural** [comment]
I looked into this little bit. And I think I solved most of the issues with your test cases. I'll open new couple of PRs that will solve the issues incrementally. Including your test cases.

**Comment by canvural** [comment]
Hi,

I just pushed bunch of changes. And I believe the issue you reported is fixed. Can you test `main` branch?

One thing though. You need to add your `@var` comment like this:
```php
/** @var string $value*/
$value = config(…);
```

**Comment by ThibaudDauce** [comment]
It's working in my project! Thanks!

I will publish a few failing test cases about other stuff today.

**Pull request closed without merging**
